const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("maktaba", {
  load: () => ipcRenderer.invoke("books:load"),
  save: (data) => ipcRenderer.invoke("books:save", data),
  saveSync: (data) => ipcRenderer.sendSync("books:saveSync", data),
  export: (data) => ipcRenderer.invoke("books:export", data),
  dataPath: () => ipcRenderer.invoke("books:dataPath"),
  pullLatest: () => ipcRenderer.invoke("books:pullLatest"),
  peekRemote: () => ipcRenderer.invoke("books:peekRemote"),
  applyData: (data) => ipcRenderer.invoke("books:applyData", data),
  publishState: () => ipcRenderer.invoke("books:publishState"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  setSettings: (s) => ipcRenderer.invoke("settings:set", s),
  setLibrarianPin: (pin) => ipcRenderer.invoke("settings:setLibrarianPin", pin),
  checkLibrarianPin: (pin) => ipcRenderer.invoke("settings:checkLibrarianPin", pin),
  authConfigured: () => ipcRenderer.invoke("auth:configured"),
  authLogin: (email, password, label) => ipcRenderer.invoke("auth:login", email, password, label),
  authLogout: () => ipcRenderer.invoke("auth:logout"),
  authHeartbeat: () => ipcRenderer.invoke("auth:heartbeat"),
  authStatus: () => ipcRenderer.invoke("auth:status"),
  authRestore: () => ipcRenderer.invoke("auth:restore"),
  authLockStatus: () => ipcRenderer.invoke("auth:lockStatus"),
  publish: (data) => ipcRenderer.invoke("publish", data),
  pickFile: (format) => ipcRenderer.invoke("file:pick", format),
  pickImage: () => ipcRenderer.invoke("file:pickImage"),
  openFile: (filePath) => ipcRenderer.invoke("file:open", filePath),
  readText: (filePath) => ipcRenderer.invoke("file:readText", filePath),
  fileExists: (filePath) => ipcRenderer.invoke("file:exists", filePath),
  downloadImage: (url, bookId) => ipcRenderer.invoke("file:downloadImage", url, bookId),
  coversDir: () => ipcRenderer.invoke("file:coversDir"),
  downloadFile: (url, kind) => ipcRenderer.invoke("file:downloadFile", url, kind),
  filesDir: () => ipcRenderer.invoke("file:filesDir"),
  searchCoverOnline: (query) => ipcRenderer.invoke("file:searchCoverOnline", query),
  version: () => ipcRenderer.invoke("app:version"),
  whatsNew: () => ipcRenderer.invoke("app:whatsNew"),
  checkUpdate: () => ipcRenderer.invoke("app:checkUpdate")
});
